name: build
on: [ push, pull_request ]
jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download sshpass
        uses: robinraju/release-downloader@v1
        with:
          repository: 'lxb007981/sshpass-win32'
          latest: true
          fileName: 'sshpass.exe'
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          spec: 'terminal_notifier.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'terminal-notifier'
          options: --onefile, --name "terminal-notifier", --windowed,